-- 1. Find total customers by countries

/* 
SELECT TOP 5
* 
FROM gold.dim_customers;
*/

SELECT
country,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- 2. Find total customers by gender

SELECT
gender,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- 3. Find total products by category

SELECT
category,
COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- 4. What is the average costs in each category?

SELECT
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;



-- 5. What is the total revenue generated for each category?

/*
SELECT TOP 5
*
FROM gold.fact_sales;


SELECT TOP 5
*
FROM gold.dim_products;
*/

SELECT
p.category,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

SELECT
p.category,
SUM(s.sales_amount) AS total_revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales s
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;




-- 6. Find total revenue is generated by each customer

SELECT
c.customer_number,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.customer_number, c.first_name, c.last_name
ORDER BY total_revenue DESC;




-- 7. What is the distribution of sold items across countries?

SELECT
c.country,
SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;